#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${B2B_DB_NAME};
    CREATE DATABASE ${B2C_DB_NAME};
    CREATE DATABASE ${MODERATION_DB_NAME};
EOSQL
