"""order_base

Revision ID: 226b0a7949d3
Revises: cd188a7c0cf3
Create Date: 2026-05-27 10:03:14.299603

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "226b0a7949d3"
down_revision: Union[str, Sequence[str], None] = "cd188a7c0cf3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.execute("CREATE SCHEMA IF NOT EXISTS orders")
	op.create_table(
		"addresses",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("country", sa.String(length=100), nullable=False),
		sa.Column("region", sa.String(length=200), nullable=True),
		sa.Column("city", sa.String(length=200), nullable=False),
		sa.Column("street", sa.String(length=200), nullable=False),
		sa.Column("building", sa.String(length=50), nullable=False),
		sa.Column("apartment", sa.String(length=50), nullable=True),
		sa.Column("postal_code", sa.String(length=20), nullable=True),
		sa.Column("recipient_name", sa.String(length=200), nullable=True),
		sa.Column("recipient_phone", sa.String(length=20), nullable=True),
		sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
		sa.Column("comment", sa.String(length=500), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="personal",
	)
	op.create_table(
		"payment_methods",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column(
			"type",
			sa.Enum("CARD", "SBP", "WALLET", name="paymentmethodtypeenum"),
			server_default="CARD",
			nullable=False,
		),
		sa.Column("card_last4", sa.String(length=4), nullable=True),
		sa.Column("card_brand", sa.String(length=20), nullable=True),
		sa.Column("is_default", sa.Boolean(), server_default="false", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="personal",
	)
	op.create_table(
		"orders",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("buyer_id", sa.UUID(), nullable=False),
		sa.Column(
			"status",
			sa.Enum(
				"CREATED",
				"PAID",
				"ASSEMBLING",
				"DELIVERING",
				"DELIVERED",
				"CANCELLED",
				"CANCEL_PENDING",
				name="orderstatusenum",
			),
			server_default="PAID",
			nullable=False,
		),
		sa.Column("number", sa.String(length=50), nullable=True),
		sa.Column("subtotal", sa.BigInteger(), server_default="0", nullable=False),
		sa.Column("delivery_cost", sa.BigInteger(), server_default="0", nullable=False),
		sa.Column("total", sa.BigInteger(), server_default="0", nullable=False),
		sa.Column("address_id", sa.UUID(), nullable=False),
		sa.Column("payment_method_id", sa.UUID(), nullable=False),
		sa.Column("comment", sa.Text(), nullable=True),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("idempotency_request_hash", sa.String(length=64), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["address_id"],
			["personal.addresses.id"],
		),
		sa.ForeignKeyConstraint(
			["buyer_id"], ["identity.users.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["payment_method_id"],
			["personal.payment_methods.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		sa.UniqueConstraint("number"),
		schema="orders",
	)
	op.create_table(
		"order_items",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("order_id", sa.UUID(), nullable=False),
		sa.Column("sku_id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("product_title", sa.String(length=255), nullable=False),
		sa.Column("sku_name", sa.String(length=255), nullable=False),
		sa.Column("quantity", sa.Integer(), nullable=False),
		sa.Column("unit_price", sa.BigInteger(), nullable=False),
		sa.Column("line_total", sa.BigInteger(), nullable=False),
		sa.Column("image_url", sa.String(length=512), nullable=True),
		sa.CheckConstraint("quantity > 0", name="chk_order_item_quantity_positive"),
		sa.CheckConstraint(
			"unit_price >= 0", name="chk_order_item_unit_price_nonnegative"
		),
		sa.ForeignKeyConstraint(["order_id"], ["orders.orders.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="orders",
	)
	op.add_column(
		"skus",
		sa.Column(
			"reserved_quantity", sa.Integer(), server_default="0", nullable=False
		),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("skus", "reserved_quantity", schema="catalog")
	op.drop_table("order_items", schema="orders")
	op.drop_table("orders", schema="orders")
	op.drop_table("payment_methods", schema="personal")
	op.drop_table("addresses", schema="personal")
	# ### end Alembic commands ###
