"""update_outbox_event_schema

Revision ID: 230e03d07b2b
Revises: 79c4c13e3d6b
Create Date: 2026-06-20 05:09:46.164300

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "230e03d07b2b"
down_revision: Union[str, Sequence[str], None] = "79c4c13e3d6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.execute("""CREATE TYPE outboxeventstatusenum AS ENUM ('PENDING', 'SENT'); """)
	op.execute("""
			ALTER TABLE events.outbox_event ADD COLUMN status outboxeventstatusenum NOT NULL;
	""")
	# op.add_column(
	# 	"outbox_event",
	# 	sa.Column(
	# 		"status",
	# 		sa.Enum("PENDING", "SENT", name="outboxeventstatusenum"),
	# 		# server_default="PENDING",
	# 		nullable=False,
	# 	),
	# 	schema="events",
	# )
	op.add_column(
		"outbox_event",
		sa.Column("sent_at", sa.DateTime(), nullable=True),
		schema="events",
	)
	op.add_column(
		"outbox_event",
		sa.Column("routing_key", sa.String(32), nullable=False),
		schema="events",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"outbox_event",
		sa.Column(
			"occured_at",
			postgresql.TIMESTAMP(timezone=True),
			autoincrement=False,
			nullable=False,
		),
		schema="events",
	)
	op.drop_column("outbox_event", "sent_at", schema="events")
	op.drop_column("outbox_event", "occurred_at", schema="events")
	op.drop_column("outbox_event", "status", schema="events")
	op.add_column(
		"inbox_events",
		sa.Column(
			"occured_at",
			postgresql.TIMESTAMP(timezone=True),
			autoincrement=False,
			nullable=False,
		),
		schema="events",
	)
	op.drop_column("inbox_events", "occurred_at", schema="events")
	# ### end Alembic commands ###
