"""add_reviews

Revision ID: 58d4747e2af4
Revises: c225ea9c8a99
Create Date: 2026-05-20 04:32:27.036921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58d4747e2af4"
down_revision: Union[str, Sequence[str], None] = "c225ea9c8a99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"reviews",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("rating", sa.Integer(), nullable=False),
		sa.Column("comment", sa.Text(), nullable=False),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("reviews", schema="catalog")
	# ### end Alembic commands ###
