"""add-session-tokens

Revision ID: 5fe243a8a56e
Revises: fa948a2ba05b
Create Date: 2026-05-09 10:08:13.531010

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5fe243a8a56e"
down_revision: Union[str, Sequence[str], None] = "fa948a2ba05b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"sessions",
		sa.Column(
			"session_id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			nullable=False,
		),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("token", sa.String(), nullable=False),
		sa.Column("refresh_token", sa.String(), nullable=False),
		sa.Column(
			"issued_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
		sa.PrimaryKeyConstraint("session_id"),
		sa.UniqueConstraint("refresh_token"),
		sa.UniqueConstraint("token"),
		schema="identity",
	)
	op.drop_constraint(
		op.f("favorites_user_id_fkey"),
		"favorites",
		schema="personal",
		type_="foreignkey",
	)
	op.create_foreign_key(
		None,
		"favorites",
		"products",
		["product_id"],
		["id"],
		source_schema="personal",
		referent_schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, "favorites", schema="personal", type_="foreignkey")
	op.create_foreign_key(
		op.f("favorites_user_id_fkey"),
		"favorites",
		"users",
		["user_id"],
		["id"],
		source_schema="personal",
		referent_schema="identity",
		ondelete="CASCADE",
	)
	op.drop_table("sessions", schema="identity")
	# ### end Alembic commands ###
