"""discount_fix

Revision ID: 6434e8a4b37e
Revises: 6723296818df
Create Date: 2026-05-30 09:44:31.668476

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6434e8a4b37e"
down_revision: Union[str, Sequence[str], None] = "6723296818df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("products", "discount", schema="catalog")
	op.add_column(
		"skus",
		sa.Column("discount", sa.Integer(), server_default="0", nullable=False),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("skus", "discount", schema="catalog")
	op.add_column(
		"products",
		sa.Column(
			"discount",
			sa.DOUBLE_PRECISION(precision=53),
			server_default=sa.text("'0'::double precision"),
			autoincrement=False,
			nullable=False,
		),
		schema="catalog",
	)
	# ### end Alembic commands ###
