"""order_status

Revision ID: 6723296818df
Revises: 226b0a7949d3
Create Date: 2026-05-28 13:03:55.438883

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "6723296818df"
down_revision: Union[str, Sequence[str], None] = "226b0a7949d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	order_status_enum = postgresql.ENUM(
		"CREATED",
		"PAID",
		"ASSEMBLING",
		"DELIVERING",
		"DELIVERED",
		"CANCELLED",
		"CANCEL_PENDING",
		name="orderstatusenum",
		create_type=False,
	)

	op.create_table(
		"order_status_history",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("order_id", sa.UUID(), nullable=False),
		sa.Column(
			"status", order_status_enum, server_default="CREATED", nullable=False
		),
		sa.Column(
			"changed_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("reason", sa.Text(), nullable=True),
		sa.ForeignKeyConstraint(
			["order_id"],
			["orders.orders.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		schema="orders",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("order_status_history", schema="orders")
	# ### end Alembic commands ###
