"""seller

Revision ID: 67fd92aeaed9
Revises: f9d0079db72b
Create Date: 2026-05-22 13:15:04.768705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "67fd92aeaed9"
down_revision: Union[str, Sequence[str], None] = "f9d0079db72b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"sellers",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("email", sa.String(), nullable=False),
		sa.Column("password_hash", sa.String(), nullable=False),
		sa.Column("first_name", sa.String(), nullable=False),
		sa.Column("last_name", sa.String(), nullable=False),
		sa.Column("middle_name", sa.String(), nullable=False),
		sa.Column("company_name", sa.String(), nullable=False),
		sa.Column("phone", sa.String(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("email"),
		sa.UniqueConstraint("password_hash"),
		sa.UniqueConstraint("phone"),
		schema="identity",
	)
	op.create_foreign_key(
		None,
		"invoices",
		"sellers",
		["seller_id"],
		["id"],
		source_schema="catalog",
		referent_schema="identity",
	)
	op.create_foreign_key(
		None,
		"products",
		"sellers",
		["seller_id"],
		["id"],
		source_schema="catalog",
		referent_schema="identity",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, "products", schema="catalog", type_="foreignkey")
	op.drop_constraint(None, "invoices", schema="catalog", type_="foreignkey")
	op.drop_table("sellers", schema="identity")
	# ### end Alembic commands ###
