"""

Revision ID: 797266451286
Revises: 6434e8a4b37e
Create Date: 2026-06-01 07:28:48.474448

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = "797266451286"
down_revision: Union[str, Sequence[str], None] = "6434e8a4b37e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	op.execute("""CREATE SCHEMA IF NOT EXISTS events;""")

	op.execute("""
		DO $$ BEGIN
			IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'eventtypeenum' 
			AND typnamespace = (SELECT oid FROM pg_namespace WHERE nspname = 'events')) 
			THEN
				CREATE TYPE events.eventtypeenum AS ENUM
				('PRODUCT_BLOCKED', 'PRODUCT_HARD_BLOCKED', 'PRODUCT_DELETED', 'SKU_OUT_OF_STOCK', 'SKU_BACK_IN_STOCK');
			END IF;
		END $$;
	""")
	op.create_table(
		"b2b_events",
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column(
			"event_type",
			postgresql.ENUM(
				"PRODUCT_BLOCKED",
				"PRODUCT_HARD_BLOCKED",
				"PRODUCT_DELETED",
				"SKU_OUT_OF_STOCK",
				"SKU_BACK_IN_STOCK",
				name="eventtypeenum",
				schema="events",
				create_type=False,
			),
			nullable=False,
		),
		sa.Column(
			"issued_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("idempotency_key"),
		schema="events",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("b2b_events", schema="events")
	# ### end Alembic commands ###
