"""favourite_available_status

Revision ID: 79c4c13e3d6b
Revises: b2f556cd45b3
Create Date: 2026-06-16 05:06:37.553068

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "79c4c13e3d6b"
down_revision: Union[str, Sequence[str], None] = "b2f556cd45b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"favorites",
		sa.Column("available", sa.Boolean(), nullable=False),
		schema="personal",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("favorites", "available", schema="personal")
	# ### end Alembic commands ###
