"""add_block_reason_schema

Revision ID: 9a7064f8074c
Revises: 797266451286
Create Date: 2026-06-01 13:08:17.766257

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a7064f8074c"
down_revision: Union[str, Sequence[str], None] = "797266451286"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"product_block_reason",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("reason", sa.Text(), nullable=False),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.add_column(
		"products",
		sa.Column("blocked_reason_id", sa.UUID(), nullable=True),
		schema="catalog",
	)
	op.create_foreign_key(
		None,
		"products",
		"product_block_reason",
		["blocked_reason_id"],
		["id"],
		source_schema="catalog",
		referent_schema="catalog",
	)

	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"b2b_events",
		"event_type",
		existing_type=sa.String(length=50),
		type_=postgresql.ENUM(
			"PRODUCT_BLOCKED",
			"PRODUCT_HARD_BLOCKED",
			"PRODUCT_DELETED",
			"SKU_OUT_OF_STOCK",
			"SKU_BACK_IN_STOCK",
			name="eventtypeenum",
			schema="events",
		),
		existing_nullable=False,
		schema="events",
	)
	op.drop_constraint(None, "products", schema="catalog", type_="foreignkey")
	op.drop_column("products", "blocked_reason_id", schema="catalog")
	op.drop_table("product_block_reason", schema="catalog")
	# ### end Alembic commands ###
