"""product_filter_values

Revision ID: aa3248c0a7d1
Revises: daa3b5b67b0a
Create Date: 2026-05-15 15:51:33.817998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aa3248c0a7d1"
down_revision: Union[str, Sequence[str], None] = "daa3b5b67b0a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"product_filter_values",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("filter_value_id", sa.UUID(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["filter_value_id"], ["catalog.filter_values.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_index(
		"idx_product_filter_value",
		"product_filter_values",
		["product_id", "filter_value_id"],
		unique=False,
		schema="catalog",
	)
	op.add_column(
		"products",
		sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("products", "deleted", schema="catalog")
	op.drop_index(
		"idx_product_filter_value", table_name="product_filter_values", schema="catalog"
	)
	op.drop_table("product_filter_values", schema="catalog")
	# ### end Alembic commands ###
