"""add_events_schemas

Revision ID: b108273977bb
Revises: 17a78564e0f8
Create Date: 2026-06-10 15:29:11.621091

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b108273977bb"
down_revision: Union[str, Sequence[str], None] = "17a78564e0f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

transactional = False


def upgrade() -> None:
	"""Upgrade schema."""
	op.drop_table("b2b_events", schema="events")

	op.execute("""
	DROP TYPE IF EXISTS eventtypeenum CASCADE;
	""")

	op.create_table(
		"inbox_events",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			nullable=False,
		),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("routing_key", sa.String(length=255), nullable=False),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"status",
			sa.Enum("PENDING", "PROCESSED", "FAILED", name="inboxeventstatusenum"),
			nullable=False,
		),
		sa.Column(
			"event_type",
			sa.String(32),
			nullable=False,
		),
		sa.Column(
			"occurred_at",
			sa.DateTime(timezone=True),
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		schema="events",
	)
	op.create_table(
		"outbox_event",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column(
			"event_type",
			sa.String(32),
			nullable=False,
		),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		schema="events",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"b2b_events",
		sa.Column("idempotency_key", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column(
			"event_type",
			postgresql.ENUM(
				"PRODUCT_BLOCKED",
				"PRODUCT_HARD_BLOCKED",
				"PRODUCT_DELETED",
				"SKU_OUT_OF_STOCK",
				"SKU_BACK_IN_STOCK",
				name="eventtypeenum",
				schema="events",
			),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"issued_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.PrimaryKeyConstraint("idempotency_key", name=op.f("b2b_events_pkey")),
		schema="events",
	)
	op.drop_table("outbox_event", schema="events")
	op.drop_table("inbox_events", schema="events")
	# ### end Alembic commands ###
