"""add_sku_discount

Revision ID: b2f556cd45b3
Revises: 6434e8a4b37e
Create Date: 2026-06-03 15:48:32.135595

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b2f556cd45b3"
down_revision: Union[str, Sequence[str], None] = "b108273977bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"skus",
		"discount",
		existing_type=sa.INTEGER(),
		type_=sa.BigInteger(),
		existing_nullable=False,
		existing_server_default=sa.text("0"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"skus",
		"discount",
		existing_type=sa.BigInteger(),
		type_=sa.INTEGER(),
		existing_nullable=False,
		existing_server_default=sa.text("0"),
		schema="catalog",
	)
	# ### end Alembic commands ###
