"""add_product_sorting_fields

Revision ID: c225ea9c8a99
Revises: aa3248c0a7d1
Create Date: 2026-05-16 06:58:29.865135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c225ea9c8a99"
down_revision: Union[str, Sequence[str], None] = "aa3248c0a7d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"products",
		sa.Column("rating", sa.Float(), server_default="0.0", nullable=False),
		schema="catalog",
	)
	op.add_column(
		"products",
		sa.Column("popularity", sa.Integer(), server_default="0", nullable=False),
		schema="catalog",
	)
	op.add_column(
		"products",
		sa.Column("discount", sa.Float(), server_default="0.0", nullable=False),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("products", "discount", schema="catalog")
	op.drop_column("products", "popularity", schema="catalog")
	op.drop_column("products", "rating", schema="catalog")
	# ### end Alembic commands ###
