"""cart_unit_price_at_add

Revision ID: cd188a7c0cf3
Revises: 67fd92aeaed9
Create Date: 2026-05-23 03:30:06.066269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd188a7c0cf3"
down_revision: Union[str, Sequence[str], None] = "67fd92aeaed9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"items",
		sa.Column("unit_price_at_add", sa.Integer(), nullable=True),
		schema="cart",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("items", "unit_price_at_add", schema="cart")
	# ### end Alembic commands ###
