"""add_token_status

Revision ID: daa3b5b67b0a
Revises: ebbb6d8840d3
Create Date: 2026-05-14 06:32:30.598397

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "daa3b5b67b0a"
down_revision: Union[str, Sequence[str], None] = "ebbb6d8840d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"sessions",
		sa.Column("is_active", sa.Boolean(), nullable=False),
		schema="identity",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("sessions", "is_active", schema="identity")
	# ### end Alembic commands ###
