"""

Revision ID: e33711a72be9
Revises: e35095731aef
Create Date: 2026-04-10 10:31:48.361901

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e33711a72be9"
down_revision: Union[str, Sequence[str], None] = "e35095731aef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"categories",
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		schema="catalog",
	)
	op.add_column(
		"categories", sa.Column("seo", sa.Text(), nullable=True), schema="catalog"
	)
	op.add_column(
		"categories",
		sa.Column("image_url", sa.String(length=255), nullable=True),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("categories", "image_url", schema="catalog")
	op.drop_column("categories", "seo", schema="catalog")
	op.drop_column("categories", "updated_at", schema="catalog")
	# ### end Alembic commands ###
