"""init

Revision ID: e35095731aef
Revises:
Create Date: 2026-04-03 15:18:13.918338

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e35095731aef"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.execute("CREATE SCHEMA IF NOT EXISTS cart")
	op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
	op.execute("CREATE SCHEMA IF NOT EXISTS identity")
	op.execute("CREATE SCHEMA IF NOT EXISTS personal")
	op.execute("CREATE SCHEMA IF NOT EXISTS storefront")
	op.create_table(
		"items",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("user_id", sa.UUID(), nullable=True),
		sa.Column("session_id", sa.String(length=255), nullable=True),
		sa.Column("sku_id", sa.UUID(), nullable=False),
		sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.CheckConstraint("quantity > 0", name="chk_cart_quantity_positive"),
		sa.CheckConstraint(
			"user_id IS NOT NULL OR session_id IS NOT NULL", name="chk_cart_identity"
		),
		sa.PrimaryKeyConstraint("id"),
		schema="cart",
	)
	op.create_index(
		"idx_cart_session", "items", ["session_id"], unique=False, schema="cart"
	)
	op.create_index("idx_cart_user", "items", ["user_id"], unique=False, schema="cart")
	op.create_index(
		"uniq_cart_session_sku",
		"items",
		["session_id", "sku_id"],
		unique=True,
		schema="cart",
		postgresql_where=sa.text("session_id IS NOT NULL"),
	)
	op.create_index(
		"uniq_cart_user_sku",
		"items",
		["user_id", "sku_id"],
		unique=True,
		schema="cart",
		postgresql_where=sa.text("user_id IS NOT NULL"),
	)
	op.create_table(
		"categories",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("parent_id", sa.UUID(), nullable=True),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["parent_id"], ["catalog.categories.id"], ondelete="SET NULL"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("slug"),
		schema="catalog",
	)
	op.create_table(
		"invoices",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("seller_id", sa.UUID(), nullable=False),
		sa.Column(
			"status",
			sa.Enum(
				"DRAFT", "PENDING", "ACCEPTED", "REJECTED", name="invoicestatusenum"
			),
			server_default="DRAFT",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"users",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column(
			"role",
			sa.Enum("SELLER", "BUYER", "ADMIN", name="roleenum"),
			server_default="BUYER",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		schema="identity",
	)
	op.create_table(
		"favorites",
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column(
			"added_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("user_id", "product_id"),
		schema="personal",
	)
	op.create_index(
		"idx_favorites_user", "favorites", ["user_id"], unique=False, schema="personal"
	)
	op.create_table(
		"subscriptions",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column(
			"notify_in_stock", sa.Boolean(), server_default="false", nullable=False
		),
		sa.Column(
			"notify_price_down", sa.Boolean(), server_default="false", nullable=False
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint(
			"user_id", "product_id", name="uniq_subscription_user_product"
		),
		schema="personal",
	)
	op.create_table(
		"banners",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("image_url", sa.String(length=512), nullable=False),
		sa.Column("link", sa.String(length=512), nullable=False),
		sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
		sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
		sa.Column("start_at", sa.DateTime(timezone=True), nullable=True),
		sa.Column("end_at", sa.DateTime(timezone=True), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		schema="storefront",
	)
	op.create_table(
		"collections",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("cover_image_url", sa.String(length=512), nullable=True),
		sa.Column("target_url", sa.String(length=512), nullable=True),
		sa.Column("priority", sa.Integer(), server_default="0", nullable=False),
		sa.Column("start_date", sa.Date(), nullable=True),
		sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id"),
		schema="storefront",
	)
	op.create_table(
		"products",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("seller_id", sa.UUID(), nullable=False),
		sa.Column("category_id", sa.UUID(), nullable=False),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column(
			"status",
			sa.Enum(
				"CREATED",
				"ON_MODERATION",
				"MODERATED",
				"BLOCKED",
				name="productstatusenum",
			),
			server_default="CREATED",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["category_id"],
			["catalog.categories.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("slug"),
		schema="catalog",
	)
	op.create_index(
		"idx_products_seller_id",
		"products",
		["seller_id"],
		unique=False,
		schema="catalog",
	)
	op.create_table(
		"collection_products",
		sa.Column("collection_id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.ForeignKeyConstraint(
			["collection_id"], ["storefront.collections.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("collection_id", "product_id"),
		schema="storefront",
	)
	op.create_table(
		"skus",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("price", sa.BigInteger(), nullable=False),
		sa.Column("active_quantity", sa.Integer(), server_default="0", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.CheckConstraint("active_quantity >= 0", name="chk_active_quantity_positive"),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"characteristics",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=True),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("value", sa.String(length=255), nullable=False),
		sa.CheckConstraint(
			"product_id IS NOT NULL OR sku_id IS NOT NULL",
			name="chk_characteristic_owner",
		),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["sku_id"], ["catalog.skus.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"images",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("url", sa.String(length=512), nullable=False),
		sa.Column("ordering", sa.Integer(), server_default="0", nullable=False),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["sku_id"], ["catalog.skus.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"invoice_items",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("invoice_id", sa.UUID(), nullable=False),
		sa.Column("sku_id", sa.UUID(), nullable=False),
		sa.Column("quantity", sa.Integer(), nullable=False),
		sa.CheckConstraint("quantity > 0", name="chk_invoice_quantity_positive"),
		sa.ForeignKeyConstraint(
			["invoice_id"], ["catalog.invoices.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["sku_id"],
			["catalog.skus.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("invoice_items", schema="catalog")
	op.drop_table("images", schema="catalog")
	op.drop_table("characteristics", schema="catalog")
	op.drop_table("skus", schema="catalog")
	op.drop_table("collection_products", schema="storefront")
	op.drop_index("idx_products_seller_id", table_name="products", schema="catalog")
	op.drop_table("products", schema="catalog")
	op.drop_table("collections", schema="storefront")
	op.drop_table("banners", schema="storefront")
	op.drop_table("subscriptions", schema="personal")
	op.drop_index("idx_favorites_user", table_name="favorites", schema="personal")
	op.drop_table("favorites", schema="personal")
	op.drop_table("users", schema="identity")
	op.drop_table("invoices", schema="catalog")
	op.drop_table("categories", schema="catalog")
	op.drop_index(
		"uniq_cart_user_sku",
		table_name="items",
		schema="cart",
		postgresql_where=sa.text("user_id IS NOT NULL"),
	)
	op.drop_index(
		"uniq_cart_session_sku",
		table_name="items",
		schema="cart",
		postgresql_where=sa.text("session_id IS NOT NULL"),
	)
	op.drop_index("idx_cart_user", table_name="items", schema="cart")
	op.drop_index("idx_cart_session", table_name="items", schema="cart")
	op.drop_table("items", schema="cart")
	op.execute("DROP SCHEMA IF EXISTS storefront")
	op.execute("DROP SCHEMA IF EXISTS personal")
	op.execute("DROP SCHEMA IF EXISTS identity")
	op.execute("DROP SCHEMA IF EXISTS catalog")
	op.execute("DROP SCHEMA IF EXISTS cart")
	# ### end Alembic commands ###
