"""

Revision ID: e7717e5be6ce
Revises: e33711a72be9
Create Date: 2026-04-11 08:45:11.094275

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7717e5be6ce"
down_revision: Union[str, Sequence[str], None] = "e33711a72be9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"category_filters",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("category_id", sa.UUID(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("type", sa.String(length=50), nullable=False),
		sa.Column("value", sa.Text(), nullable=False),
		sa.Column("min", sa.Float(), nullable=True),
		sa.Column("max", sa.Float(), nullable=True),
		sa.ForeignKeyConstraint(
			["category_id"], ["catalog.categories.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("slug"),
		schema="catalog",
	)
	op.create_table(
		"filter_values",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("filter_id", sa.UUID(), nullable=False),
		sa.Column("value", sa.String(length=255), nullable=False),
		sa.ForeignKeyConstraint(
			["filter_id"], ["catalog.category_filters.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("filter_values", schema="catalog")
	op.drop_table("category_filters", schema="catalog")
	# ### end Alembic commands ###
