"""add-missing-fk

Revision ID: ebbb6d8840d3
Revises: 5fe243a8a56e
Create Date: 2026-05-09 10:43:13.694450

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "ebbb6d8840d3"
down_revision: Union[str, Sequence[str], None] = "5fe243a8a56e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_foreign_key(
		None,
		"favorites",
		"users",
		["user_id"],
		["id"],
		source_schema="personal",
		referent_schema="identity",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, "favorites", schema="personal", type_="foreignkey")
	# ### end Alembic commands ###
