"""banner_events

Revision ID: f9d0079db72b
Revises: 58d4747e2af4
Create Date: 2026-05-22 05:04:26.359441

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9d0079db72b"
down_revision: Union[str, Sequence[str], None] = "58d4747e2af4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"banner_events",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("banner_id", sa.UUID(), nullable=False),
		sa.Column("user_id", sa.UUID(), nullable=True),
		sa.Column("event", sa.String(length=20), nullable=False),
		sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["banner_id"],
			["storefront.banners.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		schema="storefront",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("banner_events", schema="storefront")
	# ### end Alembic commands ###
