"""update_user

Revision ID: fa948a2ba05b
Revises: e7717e5be6ce
Create Date: 2026-05-08 06:52:58.299880

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "fa948a2ba05b"
down_revision: Union[str, Sequence[str], None] = "e7717e5be6ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_foreign_key(
		None,
		"items",
		"users",
		["user_id"],
		["id"],
		source_schema="cart",
		referent_schema="identity",
		ondelete="CASCADE",
	)
	op.add_column(
		"users", sa.Column("username", sa.String(), nullable=False), schema="identity"
	)
	op.add_column(
		"users", sa.Column("email", sa.String(), nullable=False), schema="identity"
	)
	op.add_column(
		"users",
		sa.Column("password_hash", sa.String(), nullable=False),
		schema="identity",
	)
	op.create_unique_constraint(None, "users", ["username"], schema="identity")
	op.create_unique_constraint(None, "users", ["email"], schema="identity")
	op.drop_column("users", "role", schema="identity")
	op.create_foreign_key(
		None,
		"favorites",
		"users",
		["user_id"],
		["id"],
		source_schema="personal",
		referent_schema="identity",
		ondelete="CASCADE",
	)
	op.create_foreign_key(
		None,
		"subscriptions",
		"users",
		["user_id"],
		["id"],
		source_schema="personal",
		referent_schema="identity",
		ondelete="CASCADE",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, "subscriptions", schema="personal", type_="foreignkey")
	op.drop_constraint(None, "favorites", schema="personal", type_="foreignkey")
	op.add_column(
		"users",
		sa.Column(
			"role",
			postgresql.ENUM("SELLER", "BUYER", "ADMIN", name="roleenum"),
			server_default=sa.text("'BUYER'::roleenum"),
			autoincrement=False,
			nullable=False,
		),
		schema="identity",
	)
	op.drop_constraint(None, "users", schema="identity", type_="unique")
	op.drop_constraint(None, "users", schema="identity", type_="unique")
	op.drop_column("users", "password_hash", schema="identity")
	op.drop_column("users", "email", schema="identity")
	op.drop_column("users", "username", schema="identity")
	op.drop_constraint(None, "items", schema="cart", type_="foreignkey")
	# ### end Alembic commands ###
