"""mod_ticket_approve

Revision ID: 524876555327
Revises: d9afb282b2f7
Create Date: 2026-06-13 05:00:53.491350

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "524876555327"
down_revision: Union[str, Sequence[str], None] = "d9afb282b2f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.execute("CREATE SCHEMA IF NOT EXISTS identity")
	op.create_table(
		"moderators",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("email", sa.String(), nullable=False),
		sa.Column("password_hash", sa.String(), nullable=False),
		sa.Column("first_name", sa.String(), nullable=False),
		sa.Column("last_name", sa.String(), nullable=True),
		sa.Column(
			"role",
			sa.Enum("MODERATOR", "ADMIN", name="moderator_role", native_enum=False),
			nullable=False,
		),
		sa.Column("is_active", sa.Boolean(), nullable=False),
		sa.Column(
			"category_specializations", postgresql.ARRAY(sa.UUID()), nullable=True
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("email"),
		schema="identity",
	)
	op.create_table(
		"outbox_events",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=128), nullable=False),
		sa.Column("routing_key", sa.String(length=255), nullable=False),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"status",
			sa.Enum("PENDING", "SENT", name="outbox_event_status", native_enum=False),
			server_default="PENDING",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
	)
	op.create_table(
		"sessions",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("user_id", sa.UUID(), nullable=False),
		sa.Column("access_token", sa.String(), nullable=False),
		sa.Column("refresh_token", sa.String(), nullable=False),
		sa.Column(
			"issued_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
		sa.Column("is_active", sa.Boolean(), nullable=False),
		sa.ForeignKeyConstraint(
			["user_id"],
			["identity.moderators.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("access_token"),
		sa.UniqueConstraint("refresh_token"),
		schema="identity",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("sessions", schema="identity")
	op.drop_table("outbox_events")
	op.drop_table("moderators", schema="identity")
	op.execute("DROP SCHEMA IF EXISTS identity")
	# ### end Alembic commands ###
