"""blocking_reasons

Revision ID: b153d29ca633
Revises: e4a2f1e63c90
Create Date: 2026-06-16 17:03:20.090757

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "b153d29ca633"
down_revision: Union[str, Sequence[str], None] = "e4a2f1e63c90"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_foreign_key(
		None,
		"tickets",
		"blocking_reasons",
		["blocking_reason_id"],
		["id"],
		ondelete="RESTRICT",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_constraint(None, "tickets", type_="foreignkey")
	# ### end Alembic commands ###
