"""init

Revision ID: d9afb282b2f7
Revises:
Create Date: 2026-06-12 05:54:41.810425

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d9afb282b2f7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	op.execute("CREATE SCHEMA IF NOT EXISTS catalog")
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"categories",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"processed_b2b_events",
		sa.Column("sender_service", sa.String(length=64), nullable=False),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=32), nullable=False),
		sa.Column(
			"processed_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("sender_service", "idempotency_key"),
	)
	op.create_table(
		"processed_catalog_events",
		sa.Column("sender_service", sa.String(length=64), nullable=False),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=32), nullable=False),
		sa.Column(
			"processed_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("sender_service", "idempotency_key"),
	)
	op.create_table(
		"tickets",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("seller_id", sa.UUID(), nullable=False),
		sa.Column("category_id", sa.UUID(), nullable=True),
		sa.Column(
			"kind",
			sa.Enum("CREATE", "EDIT", name="ticket_kind", native_enum=False),
			nullable=False,
		),
		sa.Column(
			"status",
			sa.Enum(
				"PENDING",
				"IN_REVIEW",
				"APPROVED",
				"BLOCKED",
				"HARD_BLOCKED",
				name="ticket_status",
				native_enum=False,
			),
			nullable=False,
		),
		sa.Column("queue_priority", sa.Integer(), nullable=False),
		sa.Column("total_active_quantity", sa.Integer(), nullable=False),
		sa.Column(
			"json_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True
		),
		sa.Column(
			"json_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False
		),
		sa.Column("assigned_moderator_id", sa.UUID(), nullable=True),
		sa.Column("blocking_reason_id", sa.UUID(), nullable=True),
		sa.Column("moderator_comment", sa.Text(), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("decision_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("product_id"),
	)
	op.create_table(
		"products",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("seller_id", sa.UUID(), nullable=False),
		sa.Column("category_id", sa.UUID(), nullable=False),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column(
			"status",
			sa.Enum(
				"CREATED",
				"ON_MODERATION",
				"MODERATED",
				"BLOCKED",
				"HARD_BLOCKED",
				"DELETED",
				name="product_status",
				native_enum=False,
			),
			server_default="CREATED",
			nullable=False,
		),
		sa.Column("deleted", sa.Boolean(), server_default="false", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["category_id"],
			["catalog.categories.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"ticket_field_reports",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("ticket_id", sa.UUID(), nullable=False),
		sa.Column("field_path", sa.String(length=255), nullable=False),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("message", sa.Text(), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(["ticket_id"], ["tickets.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
	)
	op.create_table(
		"skus",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("price", sa.BigInteger(), nullable=False),
		sa.Column("discount", sa.BigInteger(), server_default="0", nullable=False),
		sa.Column("active_quantity", sa.Integer(), server_default="0", nullable=False),
		sa.Column("article", sa.String(length=255), nullable=True),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"characteristics",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=True),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("value", sa.String(length=255), nullable=False),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["sku_id"], ["catalog.skus.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"images",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=True),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("url", sa.String(length=512), nullable=False),
		sa.Column("ordering", sa.Integer(), server_default="0", nullable=False),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["sku_id"], ["catalog.skus.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("images", schema="catalog")
	op.drop_table("characteristics", schema="catalog")
	op.drop_table("skus", schema="catalog")
	op.drop_table("ticket_field_reports")
	op.drop_table("products", schema="catalog")
	op.drop_table("tickets")
	op.drop_table("processed_catalog_events")
	op.drop_table("processed_b2b_events")
	op.drop_table("categories", schema="catalog")
	op.execute("DROP SCHEMA IF EXISTS catalog CASCADE")
	# ### end Alembic commands ###
