"""queue_claim

Revision ID: e4a2f1e63c90
Revises: 261215519b86
Create Date: 2026-06-14 06:19:17.538204

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e4a2f1e63c90"
down_revision: Union[str, Sequence[str], None] = "261215519b86"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"tickets", sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True)
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("tickets", "claimed_at")
	# ### end Alembic commands ###
