"""update_event_schemas_to_match_b2c

Revision ID: 07b87d405314
Revises: f1a2b3c4d5e6
Create Date: 2026-06-29 09:41:44.466261

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "07b87d405314"
down_revision: Union[str, Sequence[str], None] = "f1a2b3c4d5e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"outbox_event",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("routing_key", sa.String(length=32), nullable=False),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=32), nullable=False),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"status",
			sa.Enum("PENDING", "SENT", name="outboxeventstatusenum"),
			server_default="PENDING",
			nullable=False,
		),
		sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
		sa.Column("sent_at", sa.DateTime(), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		schema="events",
	)
	op.drop_table("outbox_events", schema="events")
	op.add_column(
		"inbox_events",
		sa.Column("event_type", sa.String(length=32), nullable=False),
		schema="events",
	)
	op.add_column(
		"inbox_events",
		sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
		schema="events",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("inbox_events", "occurred_at", schema="events")
	op.drop_column("inbox_events", "event_type", schema="events")
	op.create_table(
		"outbox_events",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("idempotency_key", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column(
			"event_type", sa.VARCHAR(length=128), autoincrement=False, nullable=False
		),
		sa.Column(
			"routing_key", sa.VARCHAR(length=255), autoincrement=False, nullable=False
		),
		sa.Column(
			"payload",
			postgresql.JSONB(astext_type=sa.Text()),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"status",
			postgresql.ENUM("PENDING", "SENT", name="outboxeventstatus"),
			server_default=sa.text("'PENDING'::outboxeventstatus"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"sent_at",
			postgresql.TIMESTAMP(timezone=True),
			autoincrement=False,
			nullable=True,
		),
		sa.PrimaryKeyConstraint("id", name=op.f("outbox_events_pkey")),
		sa.UniqueConstraint(
			"idempotency_key",
			name=op.f("outbox_events_idempotency_key_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		schema="events",
	)
	op.create_table(
		"alembic_version",
		sa.Column(
			"version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
		),
		sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
	)
	op.drop_table("outbox_event", schema="events")
	# ### end Alembic commands ###
