"""add_inbox_messages_sche,as

Revision ID: 29f73a29d3a7
Revises: bbab6851ac09
Create Date: 2026-06-09 04:52:39.838421

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "29f73a29d3a7"
down_revision: Union[str, Sequence[str], None] = "bbab6851ac09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	op.execute("""
			CREATE SCHEMA IF NOT EXISTS events;
			""")
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"inbox_events",
		sa.Column("id", sa.UUID(), nullable=False),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("routing_key", sa.String(length=255), nullable=False),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"status",
			sa.Enum("PENDING", "PROCESSED", "FAILED", name="inboxeventstatusenum"),
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		schema="events",
	)
	op.create_table(
		"outbox_events",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=128), nullable=False),
		sa.Column("routing_key", sa.String(length=255), nullable=False),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"status",
			sa.Enum("PENDING", "SENT", name="outboxeventstatus"),
			server_default="PENDING",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		schema="events",
	)
	op.drop_table("outbox_events", schema="catalog")
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"outbox_events",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("idempotency_key", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column(
			"event_type", sa.VARCHAR(length=128), autoincrement=False, nullable=False
		),
		sa.Column(
			"routing_key", sa.VARCHAR(length=255), autoincrement=False, nullable=False
		),
		sa.Column(
			"payload",
			postgresql.JSONB(astext_type=sa.Text()),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"status",
			postgresql.ENUM("PENDING", "SENT", name="outboxeventstatus"),
			server_default=sa.text("'PENDING'::outboxeventstatus"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"sent_at",
			postgresql.TIMESTAMP(timezone=True),
			autoincrement=False,
			nullable=True,
		),
		sa.PrimaryKeyConstraint("id", name=op.f("outbox_events_pkey")),
		sa.UniqueConstraint(
			"idempotency_key",
			name=op.f("outbox_events_idempotency_key_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		schema="catalog",
	)
	op.create_table(
		"alembic_version",
		sa.Column(
			"version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
		),
		sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
	)
	op.drop_table("outbox_events", schema="events")
	op.drop_table("inbox_events", schema="events")
	# ### end Alembic commands ###
