"""init_b2b

Revision ID: 3ed06920443b
Revises:
Create Date: 2026-03-27 16:54:10.548879

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3ed06920443b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.execute(sa.text("CREATE SCHEMA IF NOT EXISTS catalog"))
	op.create_table(
		"categories",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("parent_id", sa.UUID(), nullable=True),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["parent_id"], ["catalog.categories.id"], ondelete="SET NULL"
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("slug"),
		schema="catalog",
	)
	op.create_table(
		"invoices",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("seller_id", sa.UUID(), nullable=False),
		sa.Column(
			"status",
			sa.Enum(
				"DRAFT", "PENDING", "ACCEPTED", "REJECTED", name="invoicestatusenum"
			),
			server_default="DRAFT",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"products",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("seller_id", sa.UUID(), nullable=False),
		sa.Column("category_id", sa.UUID(), nullable=False),
		sa.Column("title", sa.String(length=255), nullable=False),
		sa.Column("slug", sa.String(length=255), nullable=False),
		sa.Column("description", sa.Text(), nullable=True),
		sa.Column(
			"status",
			sa.Enum(
				"CREATED",
				"ON_MODERATION",
				"MODERATED",
				"BLOCKED",
				name="productstatusenum",
			),
			server_default="CREATED",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["category_id"],
			["catalog.categories.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("slug"),
		schema="catalog",
	)
	op.create_index(
		"idx_products_seller_id",
		"products",
		["seller_id"],
		unique=False,
		schema="catalog",
	)
	op.create_table(
		"skus",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("price", sa.BigInteger(), nullable=False),
		sa.Column("active_quantity", sa.Integer(), server_default="0", nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.CheckConstraint("active_quantity >= 0", name="chk_active_quantity_positive"),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"characteristics",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=True),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("name", sa.String(length=255), nullable=False),
		sa.Column("value", sa.String(length=255), nullable=False),
		sa.CheckConstraint(
			"product_id IS NOT NULL OR sku_id IS NOT NULL",
			name="chk_characteristic_owner",
		),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["sku_id"], ["catalog.skus.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"images",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("sku_id", sa.UUID(), nullable=True),
		sa.Column("url", sa.String(length=512), nullable=False),
		sa.Column("ordering", sa.Integer(), server_default="0", nullable=False),
		sa.ForeignKeyConstraint(
			["product_id"], ["catalog.products.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(["sku_id"], ["catalog.skus.id"], ondelete="CASCADE"),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	op.create_table(
		"invoice_items",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("invoice_id", sa.UUID(), nullable=False),
		sa.Column("sku_id", sa.UUID(), nullable=False),
		sa.Column("quantity", sa.Integer(), nullable=False),
		sa.CheckConstraint("quantity > 0", name="chk_invoice_quantity_positive"),
		sa.ForeignKeyConstraint(
			["invoice_id"], ["catalog.invoices.id"], ondelete="CASCADE"
		),
		sa.ForeignKeyConstraint(
			["sku_id"],
			["catalog.skus.id"],
		),
		sa.PrimaryKeyConstraint("id"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("invoice_items", schema="catalog")
	op.drop_table("images", schema="catalog")
	op.drop_table("characteristics", schema="catalog")
	op.drop_table("skus", schema="catalog")
	op.drop_index("idx_products_seller_id", table_name="products", schema="catalog")
	op.drop_table("products", schema="catalog")
	op.drop_table("invoices", schema="catalog")
	op.drop_table("categories", schema="catalog")
	# ### end Alembic commands ###
