"""add_blocking_reasons

Revision ID: 7bea7d8e6d06
Revises: e61cbcec5a8b
Create Date: 2026-06-01 16:11:07.345986

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7bea7d8e6d06"
down_revision: Union[str, Sequence[str], None] = "e61cbcec5a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.add_column(
		"products",
		sa.Column("blocking_reason_title", sa.String(length=255), nullable=True),
		schema="catalog",
	)
	op.add_column(
		"products",
		sa.Column(
			"field_reports",
			postgresql.JSONB(astext_type=sa.Text()),
			server_default="[]",
			nullable=False,
		),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_column("products", "field_reports", schema="catalog")
	op.drop_column("products", "blocking_reason_title", schema="catalog")
	# ### end Alembic commands ###
