"""moderation_event

Revision ID: 809035676680
Revises: 52a3dd662571
Create Date: 2026-06-07 08:07:14.208914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "809035676680"
down_revision: Union[str, Sequence[str], None] = "52a3dd662571"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"moderation_processed_events",
		sa.Column("sender_service", sa.String(length=64), nullable=False),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("product_id", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=32), nullable=False),
		sa.Column(
			"processed_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("sender_service", "idempotency_key"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("moderation_processed_events", schema="catalog")
	# ### end Alembic commands ###
