"""inventory

Revision ID: bbab6851ac09
Revises: 7bea7d8e6d06
Create Date: 2026-06-04 17:29:57.149800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bbab6851ac09"
down_revision: Union[str, Sequence[str], None] = "7bea7d8e6d06"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"inventory_reserve_operations",
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("order_id", sa.UUID(), nullable=False),
		sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("idempotency_key"),
		schema="catalog",
	)
	op.create_table(
		"inventory_unreserve_operations",
		sa.Column("order_id", sa.UUID(), nullable=False),
		sa.Column(
			"processed_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.PrimaryKeyConstraint("order_id"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("inventory_unreserve_operations", schema="catalog")
	op.drop_table("inventory_reserve_operations", schema="catalog")
	# ### end Alembic commands ###
