"""message_queue_base

Revision ID: e61cbcec5a8b
Revises: f044a9704e68
Create Date: 2026-05-31 12:25:26.172670

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e61cbcec5a8b"
down_revision: Union[str, Sequence[str], None] = "f044a9704e68"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"outbox_events",
		sa.Column(
			"id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
		),
		sa.Column("idempotency_key", sa.UUID(), nullable=False),
		sa.Column("event_type", sa.String(length=128), nullable=False),
		sa.Column("routing_key", sa.String(length=255), nullable=False),
		sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
		sa.Column(
			"status",
			sa.Enum("PENDING", "SENT", name="outboxeventstatus"),
			server_default="PENDING",
			nullable=False,
		),
		sa.Column(
			"created_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
		sa.PrimaryKeyConstraint("id"),
		sa.UniqueConstraint("idempotency_key"),
		schema="catalog",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.drop_table("outbox_events", schema="catalog")
	# ### end Alembic commands ###
