"""update_image_schema

Revision ID: ebe1c33fa4b8
Revises: 83e4a34fab48
Create Date: 2026-05-22 12:12:47.036379

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ebe1c33fa4b8"
down_revision: Union[str, Sequence[str], None] = "83e4a34fab48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	op.execute("""
			CREATE TYPE public.imageentitytypeenum
			AS ENUM ('PRODUCT', 'SKU');
	""")

	# op.execute("ALTER TABLE catalog.images DROP CONSTRAINT images_product_id_fky;")
	# op.execute("ALTER TABLE catalog.images DROP CONSTRAINT images_sku_id_fky;")
	op.execute("ALTER TABLE catalog.images DROP COLUMN product_id;")
	op.execute("ALTER TABLE catalog.images DROP COLUMN sku_id;")
	op.execute("ALTER TABLE catalog.images ADD COLUMN entity_id UUID;")
	op.execute(
		"ALTER TABLE catalog.images ADD COLUMN entity_type public.imageentitytypeenum;"
	)


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.create_table(
		"invoices",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("seller_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column(
			"status",
			postgresql.ENUM(
				"DRAFT", "PENDING", "ACCEPTED", "REJECTED", name="invoicestatusenum"
			),
			server_default=sa.text("'DRAFT'::invoicestatusenum"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"accepted_at",
			postgresql.TIMESTAMP(timezone=True),
			autoincrement=False,
			nullable=True,
		),
		sa.PrimaryKeyConstraint("id", name=op.f("invoices_pkey")),
		schema="catalog",
	)
	op.create_table(
		"products",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("seller_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column("category_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.Column("slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
		sa.Column(
			"status",
			postgresql.ENUM(
				"CREATED",
				"ON_MODERATION",
				"MODERATED",
				"BLOCKED",
				"HARD_BLOCKED",
				name="productstatusenum",
			),
			server_default=sa.text("'CREATED'::productstatusenum"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"updated_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"deleted",
			sa.BOOLEAN(),
			server_default=sa.text("false"),
			autoincrement=False,
			nullable=True,
		),
		sa.Column("blocked_reason_id", sa.UUID(), autoincrement=False, nullable=True),
		sa.Column(
			"moderator_comment",
			sa.VARCHAR(length=1000),
			autoincrement=False,
			nullable=True,
		),
		sa.ForeignKeyConstraint(
			["category_id"],
			["catalog.categories.id"],
			name=op.f("products_category_id_fkey"),
		),
		sa.ForeignKeyConstraint(
			["seller_id"], ["identity.sellers.id"], name=op.f("fk_products_seller_id")
		),
		sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
		sa.UniqueConstraint(
			"slug",
			name=op.f("products_slug_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		schema="catalog",
	)
	op.create_index(
		op.f("idx_products_seller_id"),
		"products",
		["seller_id"],
		unique=False,
		schema="catalog",
	)
	op.create_table(
		"skus",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.Column("price", sa.BIGINT(), autoincrement=False, nullable=False),
		sa.Column(
			"active_quantity",
			sa.INTEGER(),
			server_default=sa.text("0"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"updated_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.CheckConstraint(
			"active_quantity >= 0", name=op.f("chk_active_quantity_positive")
		),
		sa.ForeignKeyConstraint(
			["product_id"],
			["catalog.products.id"],
			name=op.f("skus_product_id_fkey"),
			ondelete="CASCADE",
		),
		sa.PrimaryKeyConstraint("id", name=op.f("skus_pkey")),
		schema="catalog",
	)
	op.create_table(
		"alembic_version",
		sa.Column(
			"version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
		),
		sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
	)
	op.create_table(
		"sessions",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
		sa.Column("access_token", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column("refresh_token", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column(
			"issued_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=True,
		),
		sa.Column(
			"expires_at",
			postgresql.TIMESTAMP(timezone=True),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"is_active",
			sa.BOOLEAN(),
			server_default=sa.text("true"),
			autoincrement=False,
			nullable=True,
		),
		sa.ForeignKeyConstraint(
			["user_id"],
			["identity.sellers.id"],
			name=op.f("fk_sessions_user_id_sellers"),
		),
		sa.PrimaryKeyConstraint("id", name=op.f("sessions_pkey")),
		sa.UniqueConstraint(
			"access_token",
			name=op.f("uq_sessions_access_token"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		sa.UniqueConstraint(
			"refresh_token",
			name=op.f("uq_sessions_refresh_token"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		schema="identity",
	)
	op.create_table(
		"categories",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("parent_id", sa.UUID(), autoincrement=False, nullable=True),
		sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.Column("slug", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
		sa.Column(
			"is_active",
			sa.BOOLEAN(),
			server_default=sa.text("true"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(timezone=True),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["parent_id"],
			["catalog.categories.id"],
			name=op.f("categories_parent_id_fkey"),
			ondelete="SET NULL",
		),
		sa.PrimaryKeyConstraint("id", name=op.f("categories_pkey")),
		sa.UniqueConstraint(
			"slug",
			name=op.f("categories_slug_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		schema="catalog",
	)
	op.create_table(
		"characteristics",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=True),
		sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=True),
		sa.Column("name", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.Column("value", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
		sa.CheckConstraint(
			"product_id IS NOT NULL OR sku_id IS NOT NULL",
			name=op.f("chk_characteristic_owner"),
		),
		sa.ForeignKeyConstraint(
			["product_id"],
			["catalog.products.id"],
			name=op.f("characteristics_product_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["sku_id"],
			["catalog.skus.id"],
			name=op.f("characteristics_sku_id_fkey"),
			ondelete="CASCADE",
		),
		sa.PrimaryKeyConstraint("id", name=op.f("characteristics_pkey")),
		schema="catalog",
	)
	op.create_table(
		"invoice_items",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("invoice_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column("quantity", sa.INTEGER(), autoincrement=False, nullable=False),
		sa.CheckConstraint("quantity > 0", name=op.f("chk_invoice_quantity_positive")),
		sa.ForeignKeyConstraint(
			["invoice_id"],
			["catalog.invoices.id"],
			name=op.f("invoice_items_invoice_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["sku_id"], ["catalog.skus.id"], name=op.f("invoice_items_sku_id_fkey")
		),
		sa.PrimaryKeyConstraint("id", name=op.f("invoice_items_pkey")),
		schema="catalog",
	)
	op.create_table(
		"sellers",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column("password_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column("first_name", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column("last_name", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column("middle_name", sa.VARCHAR(), autoincrement=False, nullable=True),
		sa.Column("company_name", sa.VARCHAR(), autoincrement=False, nullable=False),
		sa.Column("phone", sa.VARCHAR(), autoincrement=False, nullable=True),
		sa.Column(
			"created_at",
			postgresql.TIMESTAMP(),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column(
			"updated_at",
			postgresql.TIMESTAMP(),
			server_default=sa.text("now()"),
			autoincrement=False,
			nullable=False,
		),
		sa.PrimaryKeyConstraint("id", name=op.f("sellers_pkey")),
		sa.UniqueConstraint(
			"email",
			name=op.f("sellers_email_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		sa.UniqueConstraint(
			"password_hash",
			name=op.f("sellers_password_hash_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		sa.UniqueConstraint(
			"phone",
			name=op.f("sellers_phone_key"),
			postgresql_include=[],
			postgresql_nulls_not_distinct=False,
		),
		schema="identity",
	)
	op.create_table(
		"images",
		sa.Column(
			"id",
			sa.UUID(),
			server_default=sa.text("gen_random_uuid()"),
			autoincrement=False,
			nullable=False,
		),
		sa.Column("product_id", sa.UUID(), autoincrement=False, nullable=False),
		sa.Column("sku_id", sa.UUID(), autoincrement=False, nullable=True),
		sa.Column("url", sa.VARCHAR(length=512), autoincrement=False, nullable=False),
		sa.Column(
			"ordering",
			sa.INTEGER(),
			server_default=sa.text("0"),
			autoincrement=False,
			nullable=False,
		),
		sa.ForeignKeyConstraint(
			["product_id"],
			["catalog.products.id"],
			name=op.f("images_product_id_fkey"),
			ondelete="CASCADE",
		),
		sa.ForeignKeyConstraint(
			["sku_id"],
			["catalog.skus.id"],
			name=op.f("images_sku_id_fkey"),
			ondelete="CASCADE",
		),
		sa.PrimaryKeyConstraint("id", name=op.f("images_pkey")),
		schema="catalog",
	)
	# ### end Alembic commands ###
