"""sku_price_fix

Revision ID: f044a9704e68
Revises: ebe1c33fa4b8
Create Date: 2026-05-30 10:20:07.825055

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f044a9704e68"
down_revision: Union[str, Sequence[str], None] = "ebe1c33fa4b8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	"""Upgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"images",
		"entity_type",
		existing_type=postgresql.ENUM("PRODUCT", "SKU", name="imageentitytypeenum"),
		nullable=False,
		schema="catalog",
	)
	op.alter_column(
		"images", "entity_id", existing_type=sa.UUID(), nullable=False, schema="catalog"
	)
	op.add_column(
		"invoices",
		sa.Column(
			"updated_at",
			sa.DateTime(timezone=True),
			server_default=sa.text("now()"),
			nullable=False,
		),
		schema="catalog",
	)
	op.alter_column(
		"products",
		"deleted",
		existing_type=sa.BOOLEAN(),
		nullable=False,
		existing_server_default=sa.text("false"),
		schema="catalog",
	)
	op.alter_column(
		"products",
		"moderator_comment",
		existing_type=sa.VARCHAR(length=1000),
		nullable=False,
		schema="catalog",
	)
	op.drop_constraint(
		op.f("fk_products_seller_id"), "products", schema="catalog", type_="foreignkey"
	)
	op.add_column(
		"skus",
		sa.Column("discount", sa.Integer(), server_default="0", nullable=False),
		schema="catalog",
	)
	op.add_column(
		"skus",
		sa.Column(
			"reserved_quantity", sa.Integer(), server_default="0", nullable=False
		),
		schema="catalog",
	)
	op.add_column(
		"skus",
		sa.Column("stock_quantity", sa.Integer(), server_default="0", nullable=False),
		schema="catalog",
	)
	op.add_column(
		"skus",
		sa.Column("cost_price", sa.Integer(), server_default="0", nullable=False),
		schema="catalog",
	)
	op.add_column(
		"skus",
		sa.Column("article", sa.String(length=255), nullable=False),
		schema="catalog",
	)
	op.alter_column(
		"sellers",
		"middle_name",
		existing_type=sa.VARCHAR(),
		nullable=False,
		schema="identity",
	)
	op.alter_column(
		"sellers",
		"phone",
		existing_type=sa.VARCHAR(),
		nullable=False,
		schema="identity",
	)
	op.alter_column(
		"sellers",
		"created_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
		existing_server_default=sa.text("now()"),
		schema="identity",
	)
	op.alter_column(
		"sellers",
		"updated_at",
		existing_type=postgresql.TIMESTAMP(),
		type_=sa.DateTime(timezone=True),
		existing_nullable=False,
		existing_server_default=sa.text("now()"),
		schema="identity",
	)
	op.alter_column(
		"sessions",
		"user_id",
		existing_type=sa.UUID(),
		nullable=False,
		schema="identity",
	)
	op.alter_column(
		"sessions",
		"issued_at",
		existing_type=postgresql.TIMESTAMP(timezone=True),
		nullable=False,
		existing_server_default=sa.text("now()"),
		schema="identity",
	)
	op.alter_column(
		"sessions",
		"is_active",
		existing_type=sa.BOOLEAN(),
		nullable=False,
		existing_server_default=sa.text("true"),
		schema="identity",
	)
	# ### end Alembic commands ###


def downgrade() -> None:
	"""Downgrade schema."""
	# ### commands auto generated by Alembic - please adjust! ###
	op.alter_column(
		"sessions",
		"is_active",
		existing_type=sa.BOOLEAN(),
		nullable=True,
		existing_server_default=sa.text("true"),
		schema="identity",
	)
	op.alter_column(
		"sessions",
		"issued_at",
		existing_type=postgresql.TIMESTAMP(timezone=True),
		nullable=True,
		existing_server_default=sa.text("now()"),
		schema="identity",
	)
	op.alter_column(
		"sessions", "user_id", existing_type=sa.UUID(), nullable=True, schema="identity"
	)
	op.alter_column(
		"sellers",
		"updated_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
		existing_server_default=sa.text("now()"),
		schema="identity",
	)
	op.alter_column(
		"sellers",
		"created_at",
		existing_type=sa.DateTime(timezone=True),
		type_=postgresql.TIMESTAMP(),
		existing_nullable=False,
		existing_server_default=sa.text("now()"),
		schema="identity",
	)
	op.alter_column(
		"sellers", "phone", existing_type=sa.VARCHAR(), nullable=True, schema="identity"
	)
	op.alter_column(
		"sellers",
		"middle_name",
		existing_type=sa.VARCHAR(),
		nullable=True,
		schema="identity",
	)
	op.drop_column("skus", "article", schema="catalog")
	op.drop_column("skus", "cost_price", schema="catalog")
	op.drop_column("skus", "stock_quantity", schema="catalog")
	op.drop_column("skus", "reserved_quantity", schema="catalog")
	op.drop_column("skus", "discount", schema="catalog")
	op.create_foreign_key(
		op.f("fk_products_seller_id"),
		"products",
		"sellers",
		["seller_id"],
		["id"],
		source_schema="catalog",
		referent_schema="identity",
	)
	op.alter_column(
		"products",
		"moderator_comment",
		existing_type=sa.VARCHAR(length=1000),
		nullable=True,
		schema="catalog",
	)
	op.alter_column(
		"products",
		"deleted",
		existing_type=sa.BOOLEAN(),
		nullable=True,
		existing_server_default=sa.text("false"),
		schema="catalog",
	)
	op.drop_column("invoices", "updated_at", schema="catalog")
	op.alter_column(
		"images", "entity_id", existing_type=sa.UUID(), nullable=True, schema="catalog"
	)
	op.alter_column(
		"images",
		"entity_type",
		existing_type=postgresql.ENUM("PRODUCT", "SKU", name="imageentitytypeenum"),
		nullable=True,
		schema="catalog",
	)
	op.create_table(
		"alembic_version",
		sa.Column(
			"version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False
		),
		sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
	)
	# ### end Alembic commands ###
